name: Build Python Executables

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PROJECT_VERSION: '1.0.0'  # Define version here

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python -

      - name: Configure Poetry
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry config virtualenvs.create false

      - name: Install Dependencies
        run: poetry install

      - name: Build Executable with PyInstaller
        run: poetry run pyinstaller --onefile --name coursera-scraper-${{ env.PROJECT_VERSION }} grade_verification/scripts/coursera_controller.py

      - name: Rename Executable for OS
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            mv dist/coursera-scraper-${{ env.PROJECT_VERSION }}.exe dist/coursera-scraper-${{ env.PROJECT_VERSION }}-win.exe
          else
            mv dist/coursera-scraper-${{ env.PROJECT_VERSION }} dist/coursera-scraper-${{ env.PROJECT_VERSION }}-mac
          fi

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: executable-${{ matrix.os }}-${{ env.PROJECT_VERSION }}
          path: dist/coursera-scraper-${{ env.PROJECT_VERSION }}-*
